//Generated by AIOCodeGen.
#import "ServiceGateway.h"
#import "YYCrossPlatformServiceMessageToNative.h"
 
 @implementation YYCrossPlatformServiceMessageToNative
 - (void)onCall:(void (^)(BOOL))result message:(NSString *)message {
    //Add your handler code here!
 	//TODO:
 }
 #pragma mark - Do not edit these method.
 - (void)__flutter_p_handler_MessageToNative:(NSDictionary *)args result:(void (^)(BOOL))result {
     [self onCall:result message:args[@"message"] ];
 }
 + (void)load{
     [[ServiceGateway sharedInstance] registerHandler:[YYCrossPlatformServiceMessageToNative new]];
 }
 - (NSString *)returnType{
   return @"BOOL";
 }
 - (NSString *)service{
   return @"CrossPlatformService";
 }
 @end
